name: Deploy to Server

on:
  push:
    branches:
      - master  # Автоматический запуск на пуш в ветку master
  workflow_dispatch:  # Добавляем возможность ручного запуска

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /security
            git pull origin main
            ./deploy.sh
