name: Deploy to Server with Docker

on:
  push:
    branches:
      - master
 workflow_dispatch:  # Добавляем возможность ручного запуска

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/security
          git pull origin master
          cd /root
          ./dockerDeploy.sh
